version: '3.9'

services:
  mysql_db:
    image: mysql:8.4.0
    ports:
      - '3307:3307'
    environment:
      - MYSQL_DATABASE=urbanape_db
      - MYSQL_ROOT_PASSWORD=urbanape
      - MYSQL_TCP_PORT=3307
    volumes:
      - ./data/mysql:/var/lib/mysql